[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  GIT_LFS_ENABLED = "true"
  NODE_VERSION = "22"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
